service: event-management

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'ap-south-1'}
  prismaEngine:
    offline: "node_modules/.prisma/client/*.node"
    staging: "node_modules/.prisma/client/libquery_engine-rhel*"
    prod: "node_modules/.prisma/client/libquery_engine-rhel*"

  esbuild:
    platform: "node"
    target: node16
    sourcemap: linked
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs18.x
  memorySize: 512
  timeout: 30
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    metrics: true
    cors: true

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 10
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  patterns:
    - ${self:custom.prismaEngine.${self:custom.stage}}
    - "node_modules/.prisma/client/schema.prisma"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
